version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    ignore:
      # These crates are actually transitive dependencies
      # that we just happen to use directly. Their versions
      # depend on other crate's versions, so they should
      # be updated manually.
      - dependency-name: tokio
      - dependency-name: primitive-types
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: "/examples/truffle"
    schedule:
      interval: weekly
      time: "02:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    versioning-strategy: increase
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: "/examples/hardhat"
    schedule:
      interval: weekly
      time: "02:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    versioning-strategy: increase
    rebase-strategy: disabled
