use crate::errors::{BytecodeError, LinkError};
use crate::str::{AddressHexExt, StringReplaceExt};
use hex;
use serde::de::{Error as DeError, Visitor};
use serde::{Deserialize, Deserializer};
use std::fmt::{Formatter, Result as FmtResult};
use std::mem;
use web3::types::{Address, Bytes};

/// The string representation of the byte code. Note that this must be a
/// `String` since `solc` linking requires string manipulation of the
/// bytecode string representation.
#[derive(Clone, Debug, Default)]
pub struct Bytecode(String);

impl Bytecode {
    /// Read hex bytecode representation from a string slice.
    pub fn from_str<S>(s: S) -> Result<Bytecode, BytecodeError>
    where
        S: AsRef<str>,
    {
        let s = s.as_ref();
        if s.len() == 0 {
            // special case where we have an empty string byte code.
            return Ok(Bytecode::default());
        }

        // check that we start with 0x
        if !s.starts_with("0x") {
            return Err(BytecodeError::MissingHexPrefix);
        }
        // and that the length is even
        if s.len() % 2 != 0 {
            return Err(BytecodeError::InvalidLength);
        }

        // verify that each code block is valid hex
        for block in CodeIter(&s[2..]) {
            let block = block?;

            if let Some(pos) = block.bytes().position(|b| match b {
                b'0'..=b'9' | b'a'..=b'f' | b'A'..=b'F' => false,
                _ => true,
            }) {
                return Err(BytecodeError::InvalidHexDigit(
                    block.chars().nth(pos).expect("valid pos"),
                ));
            }
        }

        Ok(Bytecode(s.to_string()))
    }

    /// Link a library into the current bytecode.
    ///
    /// # Panics
    ///
    /// Panics if an invalid library name is used (for example if it is more
    /// than 38 characters long).
    pub fn link<S>(&mut self, name: S, address: Address) -> Result<(), LinkError>
    where
        S: AsRef<str>,
    {
        let name = name.as_ref();
        if name.len() > 38 {
            panic!("invalid library name for linking");
        }

        // NOTE(nlordell): solc linking works by string search and replace of
        //   '__$name__..__' with the library address; see generated bytecode for
        //   `LinkedContract` contract for and example of how it looks like
        let placeholder = format!("__{:_<38}", name);
        let address = address.to_fixed_hex();
        let count = self.0.replace_in_place(&placeholder, &address);
        if count == 0 {
            return Err(LinkError::NotFound(name.to_string()));
        }

        Ok(())
    }

    /// Convert a bytecode into its byte representation.
    pub fn into_bytes(self) -> Result<Bytes, LinkError> {
        match self.undefined_libraries().next() {
            Some(library) => Err(LinkError::UndefinedLibrary(library.to_string())),
            None => Ok(Bytes(hex::decode(&self.0).expect("valid hex"))),
        }
    }

    /// Iterator over all libraries remaining in the bytecode.
    pub fn undefined_libraries<'a>(&'a self) -> LibIter<'a> {
        LibIter(&self.0)
    }

    /// Returns true if bytecode requires linking.
    pub fn requires_linking(&self) -> bool {
        self.undefined_libraries().next().is_some()
    }
}

/// internal type for iterating though a bytecode's string code blocks skipping
/// the `solc` linker placeholders.
struct CodeIter<'a>(&'a str);

impl<'a> Iterator for CodeIter<'a> {
    type Item = Result<&'a str, BytecodeError>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.0.is_empty() {
            return None;
        }

        match self.0.find("__") {
            Some(pos) => {
                let (block, tail) = self.0.split_at(pos);
                if tail.len() < 40 {
                    Some(Err(BytecodeError::PlaceholderTooShort))
                } else {
                    self.0 = &tail[40..];
                    Some(Ok(block))
                }
            }
            None => Some(Ok(mem::replace(&mut self.0, ""))),
        }
    }
}

/// An iterator over link placeholders in the bytecode.
pub struct LibIter<'a>(&'a str);

impl<'a> Iterator for LibIter<'a> {
    type Item = &'a str;

    fn next(&mut self) -> Option<Self::Item> {
        let pos = self.0.find("__")?;

        // NOTE(nlordell): this won't panic since we only constrcut this iterator
        //   on valid Bytecode instances where this has been verified
        let (placeholder, tail) = self.0[pos..].split_at(40);

        self.0 = tail;

        Some(placeholder.trim_matches('_'))
    }
}

impl<'de> Deserialize<'de> for Bytecode {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        deserializer.deserialize_str(BytecodeVisitor)
    }
}

/// A serde visitor for deserializing bytecode.
struct BytecodeVisitor;

impl<'de> Visitor<'de> for BytecodeVisitor {
    type Value = Bytecode;

    fn expecting(&self, f: &mut Formatter) -> FmtResult {
        write!(f, "valid EVM bytecode string representation")
    }

    fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
    where
        E: DeError,
    {
        Bytecode::from_str(v).map_err(E::custom)
    }

    fn visit_string<E>(self, v: String) -> Result<Self::Value, E>
    where
        E: DeError,
    {
        // TODO(nlordell): try to reuse this allocation
        self.visit_str(&v)
    }
}
