name: release
on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - fix-cargo-publish
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN_NEW }}
    steps:
      - uses: actions/checkout@v2
      - run: ci/deploy.sh --tag ${GITHUB_REF#refs/tags/}
